Analyze cleaned data

import libraries

In [3]:
import pandas as pd
import matplotlib . pyplot as plt

load cleaned dataset

In [4]:
df = pd.read_csv("../data/processed/taxis_clean.csv")
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,trip_duration
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,6.250000
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,7.083333
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,7.400000
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,25.866667
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,9.533333

Basic statistics

In [5]:
df.describe()

,passengers,distance,fare,tip,tolls,total,trip_duration
count,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000,6433.000000
mean,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794,14.349617
std,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570,11.643892
min,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000,0.000000
25%,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000,6.500000
50%,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000,10.900000
75%,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000,18.516667
max,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000,107.666667